config/routes.rb
Rails.application.routes.draw do

  # users routes
  get "/signup", to: "users#new"
  get "/profile", to: "users#show"
  resources :users, only: [:create]

  # sessions routes
  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  # post "/sessions", to: "sessions#create" 
  resources :sessions, only: [:create]


  # goals routes
  resources :goals, except: [:index]

  root "goals#index"
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :goals, dependent: :destroy

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    unless current_user
      redirect_to login_path
    end
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_filter :authorize, except: [:index, :show]
  
  # show All goals in our db
  def index
    @goals = Goal.all
    render :index
  end

  # form to create new goal that belongs to current_user
  def new
    @goal = Goal.new
    render :new
  end

  # creates new recipe in db that belongs to current_user
  def create
    goal = current_user.goals.create(goal_params)
    redirect_to goal_path(goal)
  end

  def show
    @goal = Goal.find(params[:id])
    render :show
  end

  def edit
    @goal = Goal.find(params[:id])
    if current_user.goals.include? @goal
    render :edit
    else
      redirect_to profile_path
    end
  end

  def update
    goal = Goal.find(params[:id])
    if current_user.goals.include? goal
      goal.update_attributes(goal_params)
      redirect_to goal_path(goal)
    else 
      redirect_to profile_path
    end
  end

  def destroy
    goal = Goal.find(params[:id])
    if current_user.goals.include? goal
      goal.delete_attributes(goal_params)
      redirect_to goal_path(goal)
    else 
      redirect_to profile_path
    end
  end

  private
    def goal_params
      params.require(:goal).permit(:description, :time_to_complete)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  # login form
  def new
    if current_user
      redirect_to profile_path
    else
      render :new
    end
  end

  # authenticate the user, set session, redirect
  def create
    user = User.find_by_email(user_params[:email])
    if user && user.authenticate(user_params[:password])
      session[:user_id] = user.id
      redirect_to profile_path
    else
      redirect_to login_path
    end
  end

  # clear session (log out user)
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private 
    def user_params
      params.require(:user).permit(:email, :password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, only: [:show]
  
  #form to create new user
  def new
    if current_user
      redirect_to profile_path
    else
      @user = User.new
      render :new
    end
  end

  # creates new user in db
  def create
    if current_user
      redirect_to profile_path
    else
      user = User.new(user_params)
      if user.save
        session[:user_id] = user.id
        redirect_to profile_path
      else
        redirect_to signup_path
      end
    end
  end

  # show current_user
  def show
    render :show
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/create.html.erb
<h1>Goals#create</h1>
<p>Find me in app/views/goals/create.html.erb</p>

app/views/goals/destory.html.erb
<h1>Delete Goal</h1>
<%= form_for @goal do |f| %>
  <%= f.text_field :description, placeholder: "Description" %><br>
  <%= f.text_field :time_to_complete, placeholder: "Desired Completion Date" %><br>
  <%= f.submit "Delete Goal" %>
<% end %>

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>
<%= form_for @goal do |f| %>
  <%= f.text_field :description, placeholder: "Description" %><br>
  <%= f.text_field :time_to_complete, placeholder: "Desired Completion Date" %><br>
  <%= f.submit "Save Goal" %>
<% end %>

app/views/goals/index.html.erb
<h1>Goals</h1>
<hr>
<% @goals.each do |goal| %>
  <p><%= goal.description %> - <%= goal.time_to_complete %> <%= link_to "View Goal", goal_path(goal)  %></p>
<% end %>

<% if current_user %>
  <%= link_to "Add New Goal", new_goal_path %>
  <% end %>

app/views/goals/new.html.erb
<h1>New Goal</h1>
<%= form_for @goal do |f| %>
  <%= f.text_field :description, placeholder: "Description" %><br>
  <%= f.text_field :time_to_complete, placeholder: "Desired Completion Date" %><br>
  <%= f.submit "Save Goal" %>
<% end %>

app/views/goals/show.html.erb
<h1><%= @goal.description %></h1>
<hr>
<p><%= @goal.time_to_complete %></p>

<% if current_user && current_user.goals.include?(@goal) %>
  <p><%= link_to "Edit Goal", edit_goal_path(@goal) %>
    <%= link_to "Delete Goal", delete_goal_path(@goal) %>
<% end %>
 

app/views/goals/update.html.erb
<h1>Goals#update</h1>
<p>Find me in app/views/goals/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <%= f.text_field :first_name, placeholder: "First Name" %><br>
  <%= f.text_field :last_name, placeholder: "Last Name" %><br>
  <%= f.email_field :email, placeholder: "Email" %><br>
  <%= f.password_field :password, placeholder: "Password" %><br>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h1>Profile Page</h1>
<div>
  <p><%= current_user.first_name %></p>
  <p><%= current_user.last_name %></p>
  <p><%= current_user.email %></p>
</div>

<%= if current_user.goals.any? %>
  <h3>My Goals</h3>
  <% current_user.goals.each do |goal| %>
    <p><%= goal.description %> - <%= goal.time_to_complete %></p>
  <% end %>
<% else %>
  <h4> You don't have any goals yet! </h4>
  <%= link_to "Add New Goal", new_goal_path %>
<% end %>